### ISSUE TITLE
Unexpected directive 'ScrollTo' imported by the module ...

### ISSUE THREAD

**Issue by drPavka** [drusso85/ng2-scroll-to#2]
When trying to include ScrollTo into the NgModule's imports array

**Comment by drusso85** [comment]
I'm unable to reproduce the problem.
Can you attach your package.json?

**Comment by drPavka** [comment]
[package .json.txt](https://github.com/drusso85/ng2-scroll-to/files/702196/package.json.txt)

**Comment by drPavka** [comment]
I've created project's module and add ScrollTo into declarations - now it's working 

//scrollto.module.ts
import {NgModule} from "@angular/core";
import {ScrollTo} from "ng2-scroll-to";


@NgModule({
  exports: [
   ScrollTo
  ],
  declarations:[
    ScrollTo
  ]
})

export class ScrollToModule {

}

//app.module.ts
....
import {ScrollToModule} from "./scrollto.module";
.....
@NgModule({
    ......
    imports: [
....
ScrollToModule,
....
