### ISSUE TITLE
Unexpected value "ScrollTo" error while using AOT compile option

### ISSUE THREAD

**Issue by alcfeoh** [drusso85/ng2-scroll-to#3]
My Angular 2 project works fine but if I want to build an AOT compiled version, I get the above error. I believe that in order to fix the issue, you would have to ship the TypeScript code instead of the JS version of the library (to be checked though).

**Comment by drusso85** [comment]
Thanks for the report. I will fix it this weekend.
The Angular team has made a lot of changes in the past months, so the package stop to work as expected.

**Comment by alcfeoh** [comment]
Awesome, thanks a lot.

**Comment by michaelschwarz-dev** [comment]
1+

**Comment by drusso85** [comment]
with 1.0.4 version aot compliance should be ok
