### ISSUE TITLE
Mistake in Readme:  Should be in declarations, not imports

### ISSUE THREAD

**Issue by adama357** [drusso85/ng2-scroll-to#4]
Following the instructions in the Readme, I originally put ScrollTo in the imports list in app.module.ts, but I kept getting the error "Uncaught Error: Unexpected directive 'ScrollTo' imported by the module 'AppModule'" 

Putting ScrollTo in the declarations list fixed the error, and it works now.  I assume this is just a mistake in the Readme.

**Comment by drusso85** [comment]
Thanks for the report. I will fix it this weekend.
The Angular team has made a lot of changes in the past months, so the package stop to work as expected.

**Comment by drusso85** [comment]
i've converted the package into an angular module and updated the README.

**Comment by adama357** [comment]
Thank you!  Fyi, while the updated code in the README is now correct, it still says above it, "Import the **directive** and add it to the **directives array** of your component."

**Comment by drusso85** [comment]
fixed the error in the README. Thank you for the report.
