### ISSUE TITLE
Dynamic scrollTargetSelector

### ISSUE THREAD

**Issue by ccondrup** [drusso85/ng2-scroll-to#6]
Bear with me as I'm quite new to Angular. I can't find a way to dynamically assign scroll targets.

Imagine a bookstore category: my.store/category/programming

````html
<div *ngFor="let book of getBooks()" [id]="'book_' + book.id">
	<div class="excerpt" (click)="expandDetails(book)"
	  scrollTo scrollTargetSelector="#book_{{book.id}}">
		{{book.excerpt}}
	</div>
	<div class="details" *ngIf="showDetails">...</div>
</div>
````

Hardcoding `scrollTargetSelector="#book_3"` works, but as soon as I add the dynamic id, I get the error 

> Can't bind to scrollTargetSelector since it is not known property of div

**What is the correct way to achieve this dynamic assigning?**
I can avoid the above error by making everything an `<a [href]=..>`, but then I have the issue that I have to preventDefault since I only want my expandDetails() method to fire, not to switch location href.

**Comment by drusso85** [comment]
Is ScrollToModule into your module imports array?
```
@NgModule({
    imports: [
         ....,
        ScrollToModule.forRoot(),
        ]
})
```

**Comment by drusso85** [comment]
Hi @ccondrup. Do you still have this problem? If yes, can you provide me with more details?

**Comment by ccondrup** [comment]
Sorry - it's a bit hard for me to recreate since refactored a lot of code. I have made another working solution, so closing this. Thanks for follow-up!
